language: python
python: 3.6.1

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install codecov


# run scripts
script:
  - coverage run -m unittest discover -s tests/
  - py.test -v && coverage html
  - coverage report
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate


after_success:
  - codecov